---
title: "Assignments"
format: html
description: |
    Assignments are an important part of the capstone project. Staying on top of completing the assignments is the key to your success. All assignments should be done with literate programming, compiled to pdf, and submitted to your GitHub repository. Grading will be done using a "reasonable person" test. That is, if a reasonable person would think your annotated bibliography is an annotated bibliography, you will get full credit.
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# GitHub.

You should be using GitHub to track your work and create a reproducible project with version control. You are welcome to use a prive repo, but I should be a collaborator (and your faculty advisor should also be a collaborator).  My GitHub username is `hardin47`. 

All of your assignments should be compiled to pdf and turned in to your GitHub repo with an apropriate title, for example, `topic.pdf`.

# Written assignments

## topic (5 pts)

In one or two paragraphs, explain the topic of your capstone project. The write-up need not be technical and should be accessible to other data science minors (even if they have not had the same
course background as you). 

For the first draft, clearly and precisely spell out both the **data** aspect of your project as well as the **advanced data-analytic method** you will incorporate. Eventually the capstone topic draft will turn into the introduction for your final write-up. At that point (but not for the first draft), it will include an explanation of the scope of the project, and its value, as well as a short introduction to the sources. It will also include definitions of technical terms needed to understand your project.

## annotated bibliography (5 pts)

A list of relevant sources (at least 3), preceded by a paragraph or so explaining which are the main sources and what you will be doing with each.
Additionally, you should have a source for your data (if you are using external data).

## 1st outline (5 pts)

A tentative outline of the titles of the major sections of your capstone project and a (short) narrative explaining what is going to go in each section.

## section draft (5 pts)

One section of your capstone project. You might turn in a full section of your capstone or you might turn in, for example, a well-described analysis that you've done.


## introduction or 2nd section (5 pts)

Revise, expand, and complete either the introduction or the previous section. Now include a title page, the section titles (from your outline), one completed section, and a bibliography.

## ethics component (5 pts)

A description of ethical challenges and how you've addressed them in your capstone project. 


## project draft (10 pts)

Using literate programming, your draft write-up should include an introduction, contextualization (e.g., literature review, background of problem, etc.), description of the data, ethical challenges and how you've addressed them, well-described analysis, ethics challenges / solutions, and conclusion.

## final write-up (25 pts)

Using literate programming, your final write-up should include an introduction, contextualization (e.g., literature review, background of problem, etc.), description of the data, ethical challenges and how you've addressed them, well-described analysis, and conclusion.
 
# Presentations


## First presentation (10 pts)

(~6-8 minutes) The presentation should introduce the audience to your project, generally. Additionally, below are some aspects of the project which would be great to report on. Not everyone will cover all of the items, it will depend on your project and where you are in the process.  Additionally, less is more. It is better to dig into one of the items below than to try to cover everything. We want to know the interesting aspects of the project.


* The context of the project (i.e., the disciplinary questions that motivate the problem.)
* Details of the data science / statistical / computer science / algorithmic model you will be applying.
* Challenges to the data collection aspect of the project. Scope of the data collection process.
* Ethical concerns about the project (collecting data, analyzing data, presenting the work publicly, etc.)
* General challenges -- what is going to be the hardest part of the project?

## Second presentation (10 pts)

(~8-10 minutes) The second presentation should be similar to the first presentation, except you'll have more to present. Same suggestion applies: it is more interesting to go into one detail of your project than to try to cover every single aspect of the project. By this point, everyone should have their data (unless, for example, collecting data is the endpoint of the project). Describing the details of the data to the class, including plots, would be an excellent second presentation.


## Final presentation (25 pts)

(~20 minutes) You will be presenting your completed project. Try to tell a story, give the most interesting aspects, don't try to include every single thing.  See the <a href = "https://ds190-capstone.netlify.app/slides/2025-09-02-writing" target = "_blank">presentation notes</a> for more suggestions.


