---
title: "Data Accessibility"
author: "Jo Hardin"
date: "September 29, 2026"
date-format: long
format:
  revealjs:
    incremental: false
    scrollable: true
    slide-number: true
    show-slide-number: all
    embed-resources: true
execute:
  echo: true
  warning: false
  message: false
---

```{r}
#| include: false

source("../_common.R")
fontawesome::fa_html_dependency()
options(pillar.width = 70)
```

## Agenda 9/1/26

1. Indigenous Data Governance: Strategies from United States Native Nations by Stephanie Russo Carroll, Desi Rodriguez-Lonebear, and Andrew Martinez
2. Operationalizing the CARE and FAIR Principles for Indigenous data futures by Stephanie Russo Carroll, Edit Herczog, Maui Hudson, Keith Russell & Shelley Stall 
3. CARE vs. FAIR
4. Data policies for publication


## Indigenous peoples

> "Indigenous communities, peoples and nations are those which, having a historical continuity with pre-invasion and pre-colonial societies that developed on their territories, consider themselves distinct from other sectors of the societies now prevailing on those territories, or parts of them. They form at present non-dominant sectors of society and are determined to preserve, develop and transmit to future generations their ancestral territories, and their ethnic identity, as the basis of their continued existence as peoples, in accordance with their own cultural patterns, social institutions and legal system" (Martinez Cobo 1982).

## Why consider Indigenous?

> Unlike racial or ethnic groups, Indigenous peoples and nations are political entities with rights and interests in data about their peoples, lands, and resources (Banerjee 2003, United Nations 2018, Rainie et al. 2019). The status as political entities is the fundamental difference in the relationship between Indigenous peoples and nations with Indigenous data, and other racial and ethnic groups’ relationships with data about their populations and peoples. (Carroll et al. 2019)

## Indigenous data

> "any facts, knowledge, or information about a Native nation and its tribal citizens, lands, resources, cultures, and communities. Information ranging from demographic profiles, to educational attainment rates, maps of sacred lands, songs, and social media activities," (Rainie et al. 2017b, p. 1) 

## Indigenous data

* information about environment, tribal citizens and community members, cultures, communities and interests (Nicerkson 2017)
* collective and individual data
* highlights that data are more fluid in an Indigenous context than they are in Western contexts
* have implications for both digital data as well as that which emerges from knowledge, language, and information

## Many Indigenous data ecosystems

* inconsistent, inaccurate, and irrelevant data for Indigenous peoples
* external control and ownership of data
* community mistrust of data resulting from exploitative research and policies
* lack of external support for data infrastructure and capability
* data that describes Indigenous peoples and lifeways through a deficit lens

(Rodriguez-Lonebear 2016, Rainie et al. 2017c, Kukutai and Taylor 2016, Walter 2016)

## Indigenous data sovereignty

> "Indigenous data sovereignty is the right of Indigenous peoples and tribes to govern the collection, ownership, and application of their own data" (Rainie et al. 2017b).



##

#### CARE Principles for Indigenous Data Governance

* **Collective Benefit** Data ecosystems shall be designed and function in ways that enable Indigenous Peoples to derive benefit from the data.
* **Authority to Control** Indigenous Peoples’ rights and interests in Indigenous data must be recognised and their authority to control such data be empowered. Indigenous data governance enables Indigenous Peoples and governing bodies to determine how Indigenous Peoples, as well as Indigenous lands, territories, resources, knowledges and geographical indicators, are represented and identified within data.
* **Responsibility** Those working with Indigenous data have a responsibility to share how those data are used to support Indigenous Peoples’ self determination and collective benefit. Accountability requires meaningful and openly available evidence of these efforts and the benefits accruing to Indigenous Peoples.
* **Ethics** Indigenous Peoples’ rights and wellbeing should be the primary concern at all stages of the data life cycle and across the data ecosystem.


##

#### FAIR Guiding Principles for scientific data management and stewardship

* **Findable** The first step in (re)using data is to find them. Metadata and data should be easy to find for both humans and computers. 
* **Accessible** Once the user finds the required data, she/he/they need to know how they can be accessed, possibly including authentication and authorisation.
* **Interoperable** The data usually need to be integrated with other data. In addition, the data need to interoperate with applications or workflows for analysis, storage, and processing.
* **Reusable** The ultimate goal of FAIR is to optimize the reuse of data. To achieve this, metadata and data should be well-described so that they can be replicated and/or combined in different settings.

## Metadata

> Metadata (or metainformation) is data (or information) that defines and describes the characteristics of other data. It often helps to describe, explain, locate, or otherwise make data easier to retrieve, use, or manage. For example, the title, author, and publication date of a book are metadata about the book. (https://en.wikipedia.org/wiki/Metadata)

## Types of metadata

* **Descriptive metadata** – the descriptive information about a resource. It is used for discovery and identification. It includes elements such as title, abstract, author, and keywords.
* **Structural metadata** – metadata about containers of data and indicates how compound objects are put together, for example, how pages are ordered to form chapters. It describes the types, versions, relationships, and other characteristics of digital materials.
* **Administrative metadata** – the information to help manage a resource, like resource type, and permissions, and when and how it was created.
* **Reference metadata** – the information about the contents and quality of statistical data.
* **Statistical metadata** – also called process data, may describe processes that collect, process, or produce statistical data.
* **Legal metadata** – provides information about the creator, copyright holder, and public licensing, if provided.

https://en.wikipedia.org/wiki/Metadata


## Scenarios


* CARE: How well does it support collective benefit, authority, responsibility, ethics?

* FAIR: How well does it support findability, accessibility, interoperability, reuse?

## Data policies for publication

* choose a journal, what does the journal requires for data archival? 
 * choose a paper, can you get the data for that manuscript?

* what (else) does the author needs to report? Is there a necessary data availability statement? 

